- README.md
Hi there,
Was reading through your documentation and noticed there is something weird here.
Line 43 is referring to the verbosity of the email output, which can only be 1 or 0.
Thought probably you moved some stuff in the config file and probably the docs is still referring to line 43 for the previous version of the file.
Guess it's gonna be line 9 now.
> Typo in docs (probably referring to an old version)

- README.md
- snapraid-aio-script.sh
- Added a title for the _SnapRAID Status_ section.
- Changed strings when the output is 0. This nonsense is gone:
-  _The number of deleted/updated files, (0), is below the threshold_
-  _The number of threshold warning(s) (0) has reached/exceeded threshold (0)_
-  _0 threshold warning(s) until the next forced sync_
- Added a string when using _Sync with threshold warning_ - before was only shown "Forced Sync"
- Moved "Sync is authorized" message for more clarity
- Minor tweaks to other messages
- Removed `clean_desc` and `service_array_setup` functions, used for container management
> Merge code for 2.8 release

- snapraid-aio-script.sh
This will remove the warning from the log output when there is no child PID to wait on.
I capitalized the OUT and ERROR vars, since these are globals.
> Skip unnecessary wait if there are no child PIDs

- script-config.sh
- snapraid-aio-script.sh
I minor change, but the idea is to reduce the use of global vars that are really locals (and thus lower-case).
As I find more like this it should simplify the code a bit.
There is one "fix" here cause I honestly could not fathom what the `sed` command was trying to do.
By running `sed 'q;....'` I understand to cause sed to quit immediately and always returns "", and thus the
warn count would always be 0. Instead it will parse the file for a number(s) and return them. It's still a
bit overkill than just reading the file directly.
> Move SYNC_WARN_COUNT to local var

- script-config.sh
- snapraid-aio-script.sh
It looks like there are tabs being mixed into the file which make it really hard to read. (see the github diff output for example)
I usually use spaces, but if tabs is what you prefer that is fine too. Just better to pick one and not mix them together.
I also commented out the two unused variables to fix shellcheck warning. When you finish this feature you can uncomment them.
> Fix indentation and shellcheck

- script-config.sh
- snapraid-aio-script.sh
**Add Healthchecks.io integration.**
Use Healthchecks.io to report script failures. 
Any "WARNING" will be reported as failure (DOWN), otherwise "UP".
Error message is reported to Healthchecks.io as well.
> Healthchecks.io

- script-config.sh
- snapraid-aio-script.sh
I made some updates to the way remote hosts are handled to allow management across multiple IP addresses. I had to change a few things in the way `IFS` was used in the config file to allow this to work. This is working to pause containers on three machines I have docker services on.
> Update to allow script to manage docker containers on multiple remote hosts

- script-config.sh
- snapraid-aio-script.sh
This allows a sync if the ratio of added to deleted files exceeds a user defined threshold, even if the delete threshold is exceeded. This is useful in the cases where files are being modified in a way that snapraid sees as adding and deleting rather than updating. Examples of this would be transcoding video files to different formats or a rolling backup service.
> Add switch to enable sync based on ratio of added to deleted files

- README.md
- script-config.sh
- snapraid-aio-script.sh
Implements a custom healthchecks.io URL, along with the associated line in the script-config.sh file. However, to maintain backward compatibility, if the variable is not set in the config file, then the main script will set it to the sensible default.
Addresses issue 32: https://github.com/auanasgheps/snapraid-aio-script/issues/32
> Add custom Healthchecks.io URL

- script-config.sh
- snapraid-aio-script.sh
Changes to allow management of both local and remote docker containers instead of one or the other.
Modified remote IFS to allow separators of `,` `:` or ` ` and updated documentation of remote services for consistency with local services.
Container management is now done with a single command for all containers, so the delay for remote may no longer be necessary. It remains in the config, but the default value is now `0`.
Reordered the `snapraid` commands after the options to align with the manual. https://www.snapraid.it/manual
Trimmed trailing spaces.
> Updates to make docker management more efficient and versitile.

- script-config.sh
Update CONFIG_VERSION to match SNAPSCRIPTVERSION, so that executing the script doesn't produce the error: "Please update your config file to the latest version. The current file is not compatible with this script!".
> Update script-config.sh to match current version

- snapraid-aio-script.sh
This PR does 3 things:
1. Fixes a few minor typos
2. Converts a places where tabs are mixed for indentation to be spaces instead
3. Trims trailing whitespace
Not trying to start a argument about space vs tabs, but the script already used ~80% spaces, and just had some tabs mixed in a few places, so I just figured it would be better to be consistent.
I have a couple actual PRs I'm still testing, but wanted to get this one up first so I could branch off of it to show just the meaningful changes in those.
> Fix a few typos and convert all whitespace to be consistent

- snapraid-aio-script.sh
bugfix on chk_updated function:
If UP_THRESHOLD is set to 0 on script-config.sh, and on a run there are no updated files (UPDATE_COUNT -eq 0), the if statement on lines 488-490 never triggers, and the script stops processing.  This is because the if statement on line 487 is evaluated and comes out with value false (UPDATE_COUNT being 0 is not less than UP_THRESHOLD also 0). 
This makes the script fail even if there are no updated files, but there are added files.
Example output error below with UP_THRESHOLD=0 set on script-config.sh:
```
SnapRAID DIFF [Mon Jun 3 16:53:10 NZST 2024]
DIFF finished [Mon Jun 3 16:53:14 NZST 2024]
SUMMARY: Equal [145372] - Added [1] - Deleted [0] - Moved [0] - Copied [0] - Updated [0]
There are no deleted files, that's fine.
WARNING! Updated files (0) …
```
> bugfix chk_updated function

- snapraid-aio-script.sh
This PR aims to better handle non-debian based Linux distros.  It does this by just testing the output of `dpkg --version` for the string `Debian`, and assumes if it's present then dpkg is installed and it can be used to install packages, and if it's not present, then it'll just warn the user that it's unable to automatically install packages.
This isn't a perfect system, so I'm very open to feedback, but it does feel like an improvement over the current state.  Right now, the script just assumes `dpkg` is available, and attempts to interpret the output from `dpkg-query` and `apg-get`.  On my openSUSE system this produces this output every time the script runs.
```
python3-markdown has not been found and will be installed...
python3-markdown installed successfully.
bc has not been found …
```
> Skip trying to install packages if dpkg isn't installed

- snapraid-aio-script.sh
Running the SnapRAID script while files are being modified (e.g. BT download) triggers a large number of warnings. When sending an email after the script has finished executing, it will fail due to `Argument list too long` because the content is too long.
> Trim file modified warnings

- snapraid-aio-script.sh
Difference count numbers longer than 8 digits are not padded with spaces (due to `%8u` formatter):
https://github.com/amadvance/snapraid/blob/c2664c6521aa7df7549a33b4a484427b2ab5f6de/cmdline/scan.c#L1983-L1989
The current regular expression however demands at least one space in front of any difference count number.
This causes `get_counts()` to fail if a single difference count number is longer than 8 digits.
The proposed change with a simplified regular expression does not require a space in front of the number.
It accepts such padding spaces, but does not require them anymore. It does require a number, which always is present.
Here is an example script to highlight the issue:
```
#!/bin/bash
set -o xtrace
echo "  327791 equal" | grep -w '^ \{1,\}[0-9]* equal' | sed 's/^ *//g' | cut -d ' …
```
> fix get_counts() not parsing large diffs

- script-config.sh
- snapraid-aio-script.sh
If hd-idle is configured and the spin-down functionality of the script is activated, the drives are spun down in the end of the script and a possible "custom hook" command is executed after that. Sometimes this command may access the drives in question and it would be preferred to execute the command before spinning down the drives. This PR adds a variable `EXECUTE_BEFORE_SPINDOWN` to the `AFTER_HOOK_CMD` section of the settings. If this variable is set to `1` , the command will be executed right before spinning down the disks instead of after.
(Another option would be to just add a third custom hook, that's executed before the spin-down. This PR already solves my use case though and I don't know if anyone else would use/need such a feature.)
> Add the option to execute the last custom hook before spinning down drives

- snapraid-aio-script.sh
Some characters in the email might not be displayed correctly. Setting the charset of the email to utf-8 solves this.
Some email programs or email providers may not display special characters correctly, if the charset is not specified in the header.
This makes sure emails are always displayed as desired – even if they contain special characters. 
Fixes #122
(Please delete options that are not relevant.)
> Set character set for email to UTF-8

- snapraid-aio-script.sh
"snapraid status" initial implementation to verify if the previous sync completed correctly before proceeding, otherwise halt the script.
Fixes #109
Moreover, if this implementation is expanded, could replace some of the checks that the script currently does
- Check if SnapRAID is already running
- Sanity check first to make sure we can access the content and parity files
(Please delete options that are not relevant.)
> use snapraid status to check if previous sync was completed

- snapraid-aio-script.sh
Will now search for content files based on lines starting with the keyword 'content', instead of occurrence of the filename 'snapraid.content'.
Please open this PR against the `dev` branch. **Do NOT** use the `master` branch, as I use it only for released code!
Prior logic for finding the snapraid.content files incorrectly included any occurrence of the word "snapraid.content", which could occur in other places in the snapraid.conf file.  Updated with a more robust regex.
Fixes #(issue)
(Please delete options that are not relevant.)
> Update code to build array of content files
